production:
  adapter: mysql2
  encoding: utf8
  database: 4am_experimental
  pool: 10
  username: root
  password: JFKssdzjFL3x
  host: 127.0.0.1
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
